import type { Metadata } from "next"
import { Fira_Code } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import "./globals.css"

const firacode = Fira_Code({
  weight: ['400', '500', '600'],
  subsets: ["latin"],
  variable: "--font-firacode"
});

export const metadata: Metadata = {
  title: "Mezorn | A minimalist typeracer",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/mezorn.svg",
        href: "/mezorn.svg"
      }
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body className={`${firacode.variable} font-mono`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          {children}
          <Toaster/>
        </ThemeProvider>
      </body>
    </html>
  );
}
